insert into role (id, role_name) values (1, 'Electrician');
insert into role (id, role_name) values (2, 'Construction Manager');
insert into role (id, role_name) values (3, 'Architect');
insert into role (id, role_name) values (4, 'Construction Manager');
insert into role (id, role_name) values (5, 'Project Manager');
insert into role (id, role_name) values (6, 'Project Manager');
insert into role (id, role_name) values (7, 'Electrician');
insert into role (id, role_name) values (8, 'Electrician');
insert into role (id, role_name) values (9, 'Subcontractor');
insert into role (id, role_name) values (10, 'Construction Foreman');
