insert into team (id, team_name) values (1, 'Povidone-Iodine Prep Pad');
insert into team (id, team_name) values (2, 'Flexall Pain Relieving');
insert into team (id, team_name) values (3, 'Multi-Symptom Cold Relief');
insert into team (id, team_name) values (4, 'IASO COVER VEIL PACT 25');
insert into team (id, team_name) values (5, 'Angel Foodcake Hand Sanitizer');
insert into team (id, team_name) values (6, 'OH Age recovery Tri Shield pact 10');
insert into team (id, team_name) values (7, 'White Ash Pollen');
insert into team (id, team_name) values (8, 'Moxatag');
insert into team (id, team_name) values (9, 'Arnica Montana Kit Refill');
insert into team (id, team_name) values (10, 'Optiray');
insert into team (id, team_name) values (11, 'KENALOG-10');
insert into team (id, team_name) values (12, 'Insects (whole body) cockroach, American Periplaneta americana');
insert into team (id, team_name) values (13, 'Treatment Set TS331955');
insert into team (id, team_name) values (14, 'Hydrogen Peroxide');
insert into team (id, team_name) values (15, 'Etoposide');
insert into team (id, team_name) values (16, 'Sani Mousse');
insert into team (id, team_name) values (17, 'Triamcinolone Acetonide');
insert into team (id, team_name) values (18, 'SHISEIDO THE MAKEUP FOUNDATION');
insert into team (id, team_name) values (19, 'Indigestion Symptom Formula');
insert into team (id, team_name) values (20, 'Metoclopramide Hydrochloride');
insert into team (id, team_name) values (21, 'EZ-Ox Plus');
insert into team (id, team_name) values (22, 'TRAMADOL HYDROCHLORIDE');
insert into team (id, team_name) values (23, 'Guinea Pig Hair');
insert into team (id, team_name) values (24, 'ISOVUE');
insert into team (id, team_name) values (25, 'CD DiorSkin Forever Flawless Perfection Fusion Wear Makeup SPF 25 - 021');
insert into team (id, team_name) values (26, 'Cefuroxime Axetil');
insert into team (id, team_name) values (27, 'LANOXIN');
insert into team (id, team_name) values (28, 'Hand Cleanse - Strawberry Pomegranate');
insert into team (id, team_name) values (29, 'Carbatrol');
insert into team (id, team_name) values (30, 'Dilatrate');
insert into team (id, team_name) values (31, 'Thymus Mercurius');
insert into team (id, team_name) values (32, 'Zolpidem Tartrate');
insert into team (id, team_name) values (33, 'Cefadroxil');
insert into team (id, team_name) values (34, 'Thyroplus');
insert into team (id, team_name) values (35, 'ULMUS PUMILA POLLEN');
insert into team (id, team_name) values (36, 'Pleo Muc Ex');
insert into team (id, team_name) values (37, 'STUDIO MOISTURE TINT');
insert into team (id, team_name) values (38, 'Citrus Cydonia 1');
insert into team (id, team_name) values (39, 'hemorrhoidal');
insert into team (id, team_name) values (40, 'LBEL COULEUR LUXE AMPLIFIER XP');
insert into team (id, team_name) values (41, 'Etodolac');
insert into team (id, team_name) values (42, 'Proctocort');
insert into team (id, team_name) values (43, 'RIXUBIS');
insert into team (id, team_name) values (44, 'SALICYLIC ACID');
insert into team (id, team_name) values (45, 'Calendula Healing');
insert into team (id, team_name) values (46, 'Blackberry');
insert into team (id, team_name) values (47, 'health mart pain relief');
insert into team (id, team_name) values (48, 'Bio Clematis');
insert into team (id, team_name) values (49, 'Inflammation I');
insert into team (id, team_name) values (50, 'Grapefruit');
insert into team (id, team_name) values (51, 'Symbyax');
insert into team (id, team_name) values (52, 'HYSAN HUO LU MEDICATED');
insert into team (id, team_name) values (53, 'HAHNEMANN HEADACHE');
insert into team (id, team_name) values (54, 'FINASTERIDE');
insert into team (id, team_name) values (55, 'Degree');
insert into team (id, team_name) values (56, 'Number Ten Mold Mixture');
insert into team (id, team_name) values (57, 'Probenecid');
insert into team (id, team_name) values (58, 'Venlafaxine Hydrochloride');
insert into team (id, team_name) values (59, 'Venlafaxine Hydrochloride');
insert into team (id, team_name) values (60, 'Foamcoat Antacid');
insert into team (id, team_name) values (61, 'Nifedipine');
insert into team (id, team_name) values (62, 'Kayexalate');
insert into team (id, team_name) values (63, 'Cold Multi-Symptom');
insert into team (id, team_name) values (64, 'THIAMINE HYDROCHLORIDE');
insert into team (id, team_name) values (65, 'Bumetanide');
insert into team (id, team_name) values (66, 'LISINOPRIL AND HYDROCHLOROTHIAZIDE');
insert into team (id, team_name) values (67, 'Anticavity');
insert into team (id, team_name) values (68, 'Treatment Set TS336437');
insert into team (id, team_name) values (69, 'Candidiasis Yeast');
insert into team (id, team_name) values (70, 'Breakout Control');
insert into team (id, team_name) values (71, 'Golden Pear Antibacterial Cleansing Hand Wash');
insert into team (id, team_name) values (72, 'Bellaskin Skin-rebirth Contour');
insert into team (id, team_name) values (73, 'Zithranol');
insert into team (id, team_name) values (74, 'Karanja Tree Sunshield SPF 30');
insert into team (id, team_name) values (75, 'Antiseptic Mouth Rinse');
insert into team (id, team_name) values (76, 'Oil-Free Acne Cleanser');
insert into team (id, team_name) values (77, 'Childrens Cough Relief');
insert into team (id, team_name) values (78, 'Lidocaine');
insert into team (id, team_name) values (79, 'Chloroquine Phosphate');
insert into team (id, team_name) values (80, 'SyAllgen');
insert into team (id, team_name) values (81, 'Bupivacaine Hydrochloride');
insert into team (id, team_name) values (82, 'Actos');
insert into team (id, team_name) values (83, 'Divalproex Sodium');
insert into team (id, team_name) values (84, 'Lamotrigine');
insert into team (id, team_name) values (85, 'Cyclobenzaprine Hydrochloride');
insert into team (id, team_name) values (86, 'Teething');
insert into team (id, team_name) values (87, 'Hydrocodone Bitartrate and Ibuprofen');
insert into team (id, team_name) values (88, 'Tamiflu');
insert into team (id, team_name) values (89, 'Clindamycin Hydrochloride');
insert into team (id, team_name) values (90, 'DG Health Maximum Strength Sleep Aid');
insert into team (id, team_name) values (91, 'Dipyridamole');
insert into team (id, team_name) values (92, 'Cephalexin');
insert into team (id, team_name) values (93, 'Sepia');
insert into team (id, team_name) values (94, 'Rue21 Coco Breeze Anti-Bacterial Hand Sanitizer');
insert into team (id, team_name) values (95, 'BF-PARADAC');
insert into team (id, team_name) values (96, 'Cat Hair, Standardized');
insert into team (id, team_name) values (97, 'Homeopathic Womens Libido');
insert into team (id, team_name) values (98, 'Mucus Relief Cold and Sinus');
insert into team (id, team_name) values (99, 'Cardiofroce');
insert into team (id, team_name) values (100, 'Olive Pollen');
